update: README, tools

diff --git a/tools/setup_project b/tools/setup_project
--- a/tools/setup_project
+++ b/tools/setup_project
@@ -22,11 +22,39 @@ function check_setting() {
 project_id=$(get_setting "ID" ../.env)
 check_setting "$project_id"
 
+# volume-paths array
+paths=(
+  "fms-admin-conf-${project_id}" "/Admin/conf/"
+  "fms-data-backups-${project_id}" "/Data/Backups/"
+  "fms-data-databases-${project_id}" "/Data/Databases/"
+  "fms-data-preferences-${project_id}" "/Data/Preferences/"
+  "fms-dbserver-extensions-${project_id}" "/Database Server/Extensions/"
+  "fms-conf-${project_id}" "/conf/"
+  "fms-http-dotconf-${project_id}" "/HTTPServer/.conf/"
+  "fms-http-conf-${project_id}" "/HTTPServer/conf/"
+  "fms-http-logs-${project_id}" "/HTTPServer/logs/"
+  "fms-logs-${project_id}" "/Logs/"
+  "fms-webpub-conf-${project_id}" "/Web Publishing/conf/"
+)
+
+# check directories
+printf "\n\e[34mChecking directories on host...\e[39m\n"
+no_dirs=0
+for ((i = 1; i < "${#paths[@]}"; i += 2)); do
+  if [[ ! -d "$parent_dir/fms-data${paths[$i]}" ]]; then
+    no_dirs=1
+    printf "\e[31mError:\e[39m missing directory %s/fms-data%s\n" "$parent_dir" "${paths[$i]}"
+  fi
+done
+
+[ $no_dirs -eq 1 ] && exit 1
+
 # todo reuse or remove old stuff
 [ -n "$project_id" ] && {
   printf "Found project name: %s\n" "${project_id}"
   old_volumes=$(docker volume ls -q --filter="name=${project_id}$")
-  [ -n "$old_volumes" ] && ./remove_project
+  [ -n "$old_volumes" ] && ./remove_project || exit 1 # todo get exit code
+#  [ $? -ne 0 ]  || exit 1
 }
 
 # set project id
@@ -57,31 +85,6 @@ esac
 
 # write to .env
 echo "ID=${project_id}" >../.env
-
-# volumes
-# todo extrenal script
-# volume-paths array
-paths=(
-  "fms-admin-conf-${project_id}" "/Admin/conf/"
-  "fms-data-backups-${project_id}" "/Data/Backups/"
-  "fms-data-databases-${project_id}" "/Data/Databases/"
-  "fms-data-preferences-${project_id}" "/Data/Preferences/"
-  "fms-dbserver-extensions-${project_id}" "/Database Server/Extensions/"
-  "fms-conf-${project_id}" "/conf/"
-  "fms-http-dotconf-${project_id}" "/HTTPServer/.conf/"
-  "fms-http-conf-${project_id}" "/HTTPServer/conf/"
-  "fms-http-logs-${project_id}" "/HTTPServer/logs/"
-  "fms-logs-${project_id}" "/Logs/"
-  "fms-webpub-conf-${project_id}" "/Web Publishing/conf/"
-)
-
-## create directories
-#printf "\n\e[34mCreating directories on host...\e[39m\n"
-#for ((i = 1; i < "${#paths[@]}"; i += 2)); do
-#  if [[ ! -d "fms-data${paths[$i]}" ]]; then
-#    mkdir -p -- "fms-data${paths[$i]}"
-#  fi
-#done
 
 # create bind volumes
 printf "\n\e[34mcreating volumes...\e[39m\n"
diff --git a/tools/start_server b/tools/start_server
--- a/tools/start_server
+++ b/tools/start_server
@@ -26,12 +26,51 @@ check_setting "$project_id"
   exit 1
 }
 
+function setup_volumes() {
+  # volume-paths array
+  paths=(
+    "fms-admin-conf-${project_id}" "/Admin/conf/"
+    "fms-data-backups-${project_id}" "/Data/Backups/"
+    "fms-data-databases-${project_id}" "/Data/Databases/"
+    "fms-data-preferences-${project_id}" "/Data/Preferences/"
+    "fms-dbserver-extensions-${project_id}" "/Database Server/Extensions/"
+    "fms-conf-${project_id}" "/conf/"
+    "fms-http-dotconf-${project_id}" "/HTTPServer/.conf/"
+    "fms-http-conf-${project_id}" "/HTTPServer/conf/"
+    "fms-http-logs-${project_id}" "/HTTPServer/logs/"
+    "fms-logs-${project_id}" "/Logs/"
+    "fms-webpub-conf-${project_id}" "/Web Publishing/conf/"
+  )
+
+  # check directories
+  printf "\n\e[34mChecking directories on host...\e[39m\n"
+  for ((i = 1; i < "${#paths[@]}"; i += 2)); do
+    if [[ ! -d "$parent_dir/fms-data${paths[$i]}" ]]; then
+      printf "Directories in fms-data do not exist!" >&2
+      exit 1
+    fi
+  done
+
+  # create bind volumes
+  printf "\n\e[34mcreating volumes...\e[39m\n"
+  for ((i = 0; i < "${#paths[@]}"; i += 2)); do
+    docker volume create --driver local -o o=bind -o type=none -o device="$parent_dir/fms-data${paths[$i + 1]}" "${paths[$i]}" || {
+      printf "error while creating docker volumes" >&2
+      exit 1
+    }
+  done
+
+  printf "\nVolumes are setup.\n"
+  #  exit 0
+
+}
+
 # check volumes
 function check_volumes() {
-    printf "WSL linux, checking bind volumes...\n"
-    if [ "$(find /mnt/wsl/docker-desktop-bind-mounts/${WSL_DISTRO_NAME}/ -maxdepth 1 -type d | wc -l)" -lt 12 ]; then
-        ./_setup_volumes
-    fi
+  printf "WSL linux, checking bind volumes...\n"
+  if [ "$(find /mnt/wsl/docker-desktop-bind-mounts/${WSL_DISTRO_NAME}/ -maxdepth 1 -type d | wc -l)" -lt 12 ]; then
+    setup_volumes
+  fi
 }
 
 if [ -f /proc/sys/kernel/osrelease ] && grep -q WSL /proc/sys/kernel/osrelease; then
@@ -40,16 +79,10 @@ else
   echo not WSL
 fi
 
-# todo: if WSL  find /mnt/wsl/docker-desktop-bind-mounts/Ubuntu-20.04/ -maxdepth 1 -type d | wc -l -lt 12
-# todo: if WSL  find /mnt/wsl/docker-desktop-bind-mounts/${WSL_DISTRO_NAME}/ -maxdepth 1 -type d | wc -l -lt 12
-# env WSL_DISTRO_NAME=Ubuntu-20.04
-#find /mnt/wsl/docker-desktop-bind-mounts/${WSL_DISTRO_NAME}/ -maxdepth 1 -type d
-#cat /var/lib/docker-desktop/mounts.data - mapping container-wsl, nicht für prüfung geeignet
-
 volume_count=$(docker volume ls -q --filter="name=${project_id}$")
-if [[ $(wc -l <<<"$volume_count") -ne 11 ]]; then
+if [[ $(wc -l <<<"$volume_count") -ne 11 ]]; then # todo get volume count from path array
   echo "setting up volumes"
-  ./_setup_volumes || exit 1
+  setup_volumes
 fi
 
 # check for docker network fms-net
